version: '3.8'

services:
  radicle-explorer-with-boards:
    image:  quay.io/radicle_in_containers/radicle-explorer-with-boards
    container_name: radicle-explorer-with-boards
    build:
      dockerfile: ./Containerfile
      context: .
      args:
        FALLBACK_PUBLIC_EXPLORER: http://localhost:3080/nodes/$host/$rid$path
        DEFAULT_LOCAL_HTTPD_PORT: 3080
        PLUGINS_RADICLE_PLANNING_BOARDS_ORIGIN: http://localhost:3090
    ports:
      - "3080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - explorer_caddy_data:/data

volumes:
  explorer_caddy_data: