version: '3.8'

services:
  radicle-explorer-with-boards:
    image:  quay.io/radicle_in_containers/radicle-explorer-with-boards
    container_name: radicle-explorer-with-boards
    build:
      dockerfile: ./Containerfile
      context: .
    ports:
      - "3080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - explorer_caddy_data:/data

volumes:
  explorer_caddy_data: