name: check-http-server
on: push

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./http-server
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: http-server -> target
      - name: Build
        run: cargo build --all-features
      - name: Run tests
        run: cargo test --all-features
  docs:
    name: Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./http-server
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: http-server -> target
      - name: Docs
        run: cargo doc --all --all-features
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./http-server
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: http-server -> target
      - name: Run clippy
        run: cargo clippy --all --tests
      - name: Check formatting
        run: cargo fmt --all --check
