name: check-http-client-unit-test
on: push

jobs:
  check-http-client-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - name: Install Radicle binaries
        run: |
          mkdir -p tests/artifacts;
          ./scripts/install-binaries;
          ./scripts/install-binaries --show-path >> $GITHUB_PATH;
      - run: |
          npm run test:http-client:unit
